version: '3.8'

services:
  mongo:
    container_name: file-upload-aluxion-db
    image: mongo:5.0.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
